### PR TITLE
Added Baseball Stars 2 and Crouching Tiger Hidden Dragon 2003

### PR DESCRIPTION
**Pull request by hanasu**
These were tested by myself and Fightcade users artistoflegacy and jetstream_02um. I have tried to follow the savestate creation suggestions, hopefully I have done so.

### CODE REVIEW

**Comment by 3xcl4m4t10n** [comment]
My two cents: What's the point to add this games? I mean, who are the people that's going to play these? We have a lot of empty rooms now and I see pointless add more empty rooms that create more traffic. If add more rooms does not make more traffic (not sure how Fightcade handle it) I still don't see the point but is OK.

Just my point of view.

**Comment by poliva** [comment]
Empty rooms don't create more traffic, it doesn't cost anything to add new (supported) games. Even if they are not popular it's ok to have them, I'm pretty sure some nostalgic will be happy to play them some day :+1:

**Comment by 3xcl4m4t10n** [comment]
Ok, how can I download the savestates to check it out?

**Comment by poliva** [comment]
just click on the filename in the main page, the pull request has been merged (or open fightcade and they should sync automatically).

**Comment by 3xcl4m4t10n** [comment]
For some reason, the first time i checked Fightcade did not downloaded the files so that's why i was thinking they was not alive yet.

I checked both and put it on the "Fightcade style". Enjoy! :D

https://mega.co.nz/#!mZFV2SaJ!s-oolH6wMnRt9xqWIcriZZPecSoaWnCE235iH64zV_U
https://mega.co.nz/#!CBVmAaDb!umPqS7Yq7VfkXjLTpdBaH7vzKTtiEfJI37yChPqv-rI

**Pull request merged**
